openapi: 3.0.0
info:
  version: 0.1.0
  title: Central Operations Private API
  license:
    name: MIT
    url: 'https://opensource.org/licenses/MIT'
  description: Component responsible for enrolling and monitoring participants in the Bürokratt network.
servers:
  - url: 'http://localhost:8085'
tags:
  - name: admins
    description: Secured Admin-only calls
paths:
  /invitation:
    post:
      tags:
        - admins
      summary: creates an invitation
      operationId: invitation
      description: Creates an invitation and returns the id for it
      parameters: 
        - in: cookie
          name: customJwtCookie
          schema:
            type: string
            format: jwt
          required: true
      responses:
        '200':
          description: item created, responds with the invitation ID
        '400':
          description: User email is required
        '401':
          description: unauthorized
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Invitation'
        description: User e-mail to create an invitation ID for
components:
  schemas:
    Invitation:
      type: object
      required:
        - contact_email
      properties:
        contact_email:
          type: string
          format: email
          example: admin@admin.ee
