openapi: 3.0.0
info:
  version: 0.1.0
  title: Central Operations Public API
  license:
    name: MIT
    url: 'https://opensource.org/licenses/MIT'
  description: Publicly accessible component responsible for enrolling and monitoring participants in the Bürokratt network.
servers:
  - url: 'http://localhost:8084'
tags:
  - name: public
    description: Operations available publicly
paths:
  /validate-invitation-id:
    post:
      tags:
        - public
      summary: validates invitation id
      operationId: validate-invitation-id
      description: Validates invitation id and if invitation id is valid responds with a Set-Cookie header for further requests
      responses:
        '200':
          description: invitation id validated, responds with a Set-Cookie header
        '400':
          description: Invitation id missing
        '404':
          description: Invalid id
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ValidateId'
        description: Invitation id to be validated by API
  /institution:
    post:
      tags:
        - public
      summary: sends an application to become a Bürokratt member
      operationId: institution
      description: Creates a new institution with status SUBMITTED to indicate this is a not-yet-approved application
      responses:
        '200':
          description: Application saved successfully
        '400':
          description: Any of the missing parameters is missing
        '404':
          description: Invitation id is not valid
        '401':
          description: Unauhtorized
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateInstitution'
        description: Application to create a new institution
components:
  schemas:
    ValidateId:
      type: object
      required:
        - invitation_id
      properties:
        invitation_id:
          type: string
          format: UUID
          example: '51ad3304-a286-4232-bd30-31c7333e03c4'
    CreateInstitution:
      type: object
      required:
        - email
        - organisation_name
        - invitation_id
      properties:
        user_email:
          type: string
          format: email
          example: admin@admin.ee
        organisation_name:
          type: string
          example: Riigi Infosüsteemi Amet
        invitation_id:
          type: string
          format: UUID
          example: '51ad3304-a286-4232-bd30-31c7333e03c4'
