version: '3.9'
services:
  ruuter:
    container_name: ruuter
    image: ruuter
    environment:
      - application.cors.allowedOrigins=http://localhost:3006
      - application.httpCodesAllowList=200,201,202,203,204,205,206,207,208,226
      - application.logging.displayRequestContent=true
      - application.logging.displayResponseContent=true
      - server.port=8085
      - application.DSL.processedFiletypes=.yml,.yaml,.tmp
    volumes:
      - ./DSL/Ruuter:/DSL
    ports:
      - 8085:8085
    networks:
      - bykstack
  resql:
    container_name: resql
    image: resql
    depends_on:
      - database
    environment:
      - sqlms.datasources.[0].name=centops
      - sqlms.datasources.[0].jdbcUrl=jdbc:postgresql://database:5432/centops_db
      - sqlms.datasources.[0].username=byk
      - sqlms.datasources.[0].password=01234
      - logging.level.org.springframework.boot=INFO
      - server.port=8087
    ports:
      - 8087:8087
    volumes:
      - ./DSL/Resql/centops:/workspace/app/templates/centops
    networks:
      - bykstack
  database:
    container_name: database
    image: postgres:14.1
    environment:
      - POSTGRES_USER=byk
      - POSTGRES_PASSWORD=01234
      - POSTGRES_MULTIPLE_DATABASES=centops_db
    ports:
      - 5433:5432
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./init-databases.sh:/docker-entrypoint-initdb.d/init-databases.sh
    networks:
      - bykstack
  data_mapper:
    container_name: data_mapper
    image: datamapper-node
    environment:
      - PORT=3005
      - CONTENT_FOLDER=/data
    volumes:
      - ./DSL:/data
      - ./DSL/DMapper/hbs:/workspace/app/views/centops
      - ./DSL/DMapper/js:/workspace/app/js/centops
      - ./DSL/DMapper/lib:/workspace/app/lib
      - ./secrets:/data/secrets
    ports:
      - 3005:3005
    networks:
      - bykstack
  gui_dev:
    container_name: gui_dev
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=http://localhost:8085
      - PORT=3006
    build:
      context: ./GUI
      dockerfile: Dockerfile.dev
    ports:
      - 3006:3006
    volumes:
      - /app/node_modules
      - ./GUI:/app
    networks:
      - bykstack

volumes:
  opensearch-data1:


networks:
  bykstack:
    name: bykstack
    driver: bridge
