version: '3.9'
services:
  ruuter-private:
    container_name: ruuter-private
    image: ruuter
    environment:
      - application.cors.allowedOrigins=http://localhost:8057,https://tim.buerokratt.ee
      - application.httpCodesAllowList=200,201,202,203,204,205,206,207,208,226
      - application.logging.displayRequestContent=true
      - application.logging.displayResponseContent=true
      - server.port=8050
      - application.DSL.processedFiletypes=.yml,.yaml,.tmp
    volumes:
      - ./DSL/Ruuter.private:/DSL
      - ./constants.ini:/app/constants.ini
    ports:
      - 8050:8050
    networks:
      - bykstack

  ruuter-public:
    container_name: ruuter-public
    image: ruuter
    environment:
      - application.cors.allowedOrigins=http://localhost:8058,https://tim.buerokratt.ee
      - application.httpCodesAllowList=200,201,202,203,204,205,206,207,208,226
      - application.logging.displayRequestContent=true
      - application.logging.displayResponseContent=true
      - server.port=8051
      - application.DSL.processedFiletypes=.yml,.yaml,.tmp
    volumes:
      - ./DSL/Ruuter.public:/DSL
      - ./constants.ini:/app/constants.ini
    ports:
      - 8051:8051
    networks:
      - bykstack

  resql:
    container_name: resql
    image: resql
    depends_on:
      - database
    environment:
      - sqlms.datasources.[0].name=byk
      - sqlms.datasources.[0].jdbcUrl=jdbc:postgresql://database:5432/centops_db
      - sqlms.datasources.[0].username=byk
      - sqlms.datasources.[0].password=01234
      - logging.level.org.springframework.boot=INFO
      - server.port=8052
    ports:
      - 8052:8052
    volumes:
     - ./DSL/Resql:/DSL
    networks:
      - bykstack 

  resql-users:
    container_name: resql-users
    image: resql
    depends_on:
      - database
    environment:
      - server.port=8059
      - sqlms.datasources.[0].name=byk
      # - sqlms.datasources.[0].jdbcUrl=jdbc:postgresql://database:5432/users_db
      - sqlms.datasources.[0].jdbcUrl=jdbc:postgresql://171.22.247.13:5433/byk
      - sqlms.datasources.[0].username=byk
      - sqlms.datasources.[0].password=2nH09n6Gly
      - logging.level.org.springframework.boot=INFO
    ports:
      - 8059:8059
    volumes:
      - ./DSL/Resql:/DSL
    networks:
      - bykstack    

  database:
    container_name: database
    image: postgres:14.1
    environment:
      - POSTGRES_USER=byk
      - POSTGRES_PASSWORD=01234
      - POSTGRES_MULTIPLE_DATABASES=users_db,centops_db
    ports:
      - 8053:5432
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./init-databases.sh:/docker-entrypoint-initdb.d/init-databases.sh
    networks:
      - bykstack

  data-mapper:
    container_name: data-mapper
    image: data-mapper
    environment:
      - PORT=8054
      - CONTENT_FOLDER=/data
    volumes:
      - ./DSL/DMapper/centops/hbs:/workspace/app/views/centops
      - ./DSL/DMapper/centops/js:/workspace/app/js/centops
      - ./DSL/Data/Forms:/data/forms
      - ./DSL/Data/Validation:/data/validators
    ports:
      - 8054:8054
    networks:
      - bykstack

  tim:
    container_name: tim
    image: tim
    depends_on:
      - tim-postgresql
    environment:
      - SECURITY_ALLOWLIST_JWT=resql,tim,tim-postgresql,ruuter-private,ruuter-public,data-mapper,gui_dev_private,gui_dev_public,127.0.0.1,::1
      - JWT_INTEGRATION_SIGNATURE_KEY_STORE_PASSWORD=defaultpassword
    ports:
      - 8085:8085
    networks:
      - bykstack
    extra_hosts:
      - "host.docker.internal:host-gateway"
    cpus: 0.5 #(Example CPU limit)
    mem_limit: "512M" #(Example memory limit)    

  tim-postgresql:
    container_name: tim-postgresql
    image: postgres:14.1
    environment:
      - POSTGRES_USER=tim
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=tim
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./tim-db:/var/lib/postgresql/data
    ports:
      - 9876:5432
    networks:
      - bykstack

  gui_dev_private:
    container_name: gui_dev_private
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=http://localhost:8050/centops
      - REACT_APP_PUBLIC_URL=http://localhost:8058/centops
      - PORT=8057
    build:
      context: ./GUI.private
      dockerfile: Dockerfile.dev
    ports:
      - 8057:8057
    volumes:
      - /app/node_modules
      - ./GUI.private:/app
    networks:
      - bykstack

  gui_dev_public:
    container_name: gui_dev_public
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=http://localhost:8051/centops
      - PORT=8058
    build:
      context: ./GUI.public
      dockerfile: Dockerfile.dev
    ports:
      - 8058:8058
    volumes:
      - /app/node_modules
      - ./GUI.public:/app
    networks:
      - bykstack

volumes:
  opensearch-data1:

networks:
  bykstack:
    name: bykstack
    driver: bridge
