version: '3.9'
services:
  ruuter:
    container_name: ruuter
    image: ruuter
    depends_on:
      - vault-agent
    environment:
      - application.cors.allowedOrigins=http://localhost:8057,https://tim.buerokratt.ee
      - application.httpCodesAllowList=200,201,202,203,204,205,206,207,208,226
      - application.logging.displayRequestContent=true
      - application.logging.displayResponseContent=true
      - server.port=8050
      - application.DSL.processedFiletypes=.yml,.yaml,.tmp
      - application.incomingRequests.allowedMethodTypes=GET,POST,PUT,DELETE
    volumes:
      - ./DSL/Ruuter:/DSL
      - ./constants.ini:/app/constants.ini
    ports:
      - 8050:8050
    networks:
      - bykstack

  resql:
    container_name: resql
    image: resql
    depends_on:
      - database
      - vault-agent
    environment:
      - logging.level.org.springframework.boot=INFO
      - server.port=8052
    env_file:
      - "${VAULT_DATA_PATH}/resql.env"
    ports:
      - 8052:8052
    volumes:
     - ./DSL/Resql:/DSL
    networks:
      - bykstack

  resql-users:
    container_name: resql-users
    image: resql
    depends_on:
      - database
      - vault-agent
    env_file:
      - "${VAULT_DATA_PATH}/resql-users.env"
    environment:
      - server.port=8059
      - logging.level.org.springframework.boot=INFO
    ports:
      - 8059:8059
    volumes:
      - ./DSL/Resql:/DSL
    networks:
      - bykstack

  database:
    container_name: database
    image: postgres:14.1
    depends_on:
      - vault-agent
    env_file:
      - "${VAULT_DATA_PATH}/database.env"
    ports:
      - 8053:5432
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./init-databases.sh:/docker-entrypoint-initdb.d/init-databases.sh
    networks:
      - bykstack

  data-mapper:
    container_name: data-mapper
    image: data-mapper
    environment:
      - PORT=8054
      - CONTENT_FOLDER=/data
    volumes:
      - ./DSL/DMapper/centops/hbs:/workspace/app/views/centops
      - ./DSL/DMapper/centops/js:/workspace/app/js/centops
      - ./DSL/Data/Forms:/data/forms
      - ./DSL/Data/Validation:/data/validators
    ports:
      - 8054:8054
    networks:
      - bykstack

  tim:
    container_name: tim
    image: tim
    depends_on:
      - tim-postgresql
    environment:
      - SECURITY_ALLOWLIST_JWT=resql,tim,tim-postgresql,ruuter,data-mapper,gui_dev,localhost,127.0.0.1,::1
      - JWT_INTEGRATION_SIGNATURE_KEY_STORE_PASSWORD=defaultpassword
    ports:
      - 8085:8085
    networks:
      - bykstack
    extra_hosts:
      - "host.docker.internal:host-gateway"
    cpus: 0.5 #(Example CPU limit)
    mem_limit: "512M" #(Example memory limit)

  tim-postgresql:
    container_name: tim-postgresql
    image: postgres:14.1
    depends_on:
      - vault-agent
    env_file:
      - "${VAULT_DATA_PATH}/tim-postgresql.env"
    volumes:
      - ./tim-db:/var/lib/postgresql/data
    ports:
      - 9876:5432
    networks:
      - bykstack

  gui_dev:
    container_name: gui_dev
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=http://localhost:8050/centops
      - REACT_APP_PUBLIC_URL=http://localhost:8058/centops
      - PORT=8057
    build:
      context: GUI
      dockerfile: Dockerfile.dev
    ports:
      - 8057:8057
    volumes:
      - /app/node_modules
      - ./GUI:/app
    networks:
      - bykstack

  vault:
    image: hashicorp/vault:1.18
    container_name: vault
    restart: on-failure
    ports:
      - "8200:8200"
    environment:
      VAULT_ADDR: "http://0.0.0.0:8200"
    volumes:
      - ./vault/config.hcl:/vault/config/config.hcl
      - "${VAULT_DATA_PATH}/data:/vault/data"
    entrypoint: >
      vault server -config=/vault/config/config.hcl
    cap_add:
      - IPC_LOCK
    networks:
      - bykstack

  vault-agent:
    image: hashicorp/vault:1.18
    container_name: vault-agent
    depends_on:
      - vault
    cap_add:
      - IPC_LOCK
    volumes:
      - ./vault/vault-agent.hcl:/vault/vault-agent.hcl
      - ./vault/templates/resql-template.ctmpl:/vault/templates/resql-template.ctmpl
      - ./vault/templates/resql-users-template.ctmpl:/vault/templates/resql-users-template.ctmpl
      - ./vault/templates/database-template.ctmpl:/vault/templates/database-template.ctmpl
      - ./vault/templates/tim-postgresql-template.ctmpl:/vault/templates/tim-postgresql-template.ctmpl
      - "${VAULT_DATA_PATH}/.vault-token:/vault/secrets/.vault-token:ro"
      - "${VAULT_DATA_PATH}:/vault/secrets"
    command: vault agent -config=/vault/vault-agent.hcl

  vault-unseal:
    image: curlimages/curl:8.1.0
    container_name: vault-unseal-tool
    depends_on:
      - vault
    environment:
      VAULT_UNSEAL_KEY: ${VAULT_UNSEAL_KEY}
    entrypoint: sh
    command: -c '
      echo "Waiting for Vault to be started...";
      until curl --silent http://vault:8200/v1/sys/health | grep -q "\"initialized\":true"; do
      sleep 2;
      done;
      echo "Sending unseal key...";
      curl --silent --request PUT --data "{\"key\":\"$VAULT_UNSEAL_KEY\"}" http://vault:8200/v1/sys/unseal;
      echo "Vault Unseal done.";'

    restart: "no"

volumes:
  opensearch-data1:
  vault-data:

networks:
  bykstack:
    name: bykstack
    driver: bridge
