apiVersion: apps/v1
kind: Deployment
metadata:
  name: resql-users
  namespace: {{ .Values.namespace }}
  labels:
    app: resql-users
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resql-users
  template:
    metadata:
      labels:
        app: resql-users
    spec:
      containers:
      - name: resql-users
        image: {{ .Values.images.resql.repository }}:{{ .Values.images.resql.tag }}
        imagePullPolicy: {{ .Values.images.resql.pullPolicy }}
        ports:
        - containerPort: {{ .Values.ports.resqlUsers }}
        env:
        - name: logging.level.org.springframework.boot
          value: {{ .Values.resqlUsers.env.loggingLevel | quote }}
        - name: server.port
          value: {{ .Values.ports.resqlUsers | quote }}
        envFrom:
        - configMapRef:
            name: vault-config
            key: resql-users.env
        volumeMounts:
        - name: dsl
          mountPath: /DSL
        - name: secrets
          mountPath: /vault/secrets
      volumes:
      - name: dsl
        emptyDir: {}
      - name: secrets
        emptyDir: {}
      initContainers:
      - name: git-clone
        image: alpine/git:latest
        volumeMounts:
        - name: dsl
          mountPath: /DSL
        command:
          - sh
          - -c
          - |
            if [ ! -d "/DSL/users" ]; then
              git clone --single-branch --depth 1 --branch helm-charts https://github.com/varmoh/CentOps.git /tmp/CentOps &&
              cp -r /tmp/CentOps/DSL/Resq/users /DSL/;
            else
              echo "centops folder already present, skipping clone.";
            fi   
      - name: wait-for-database
        image: {{ .Values.images.curl.repository }}:{{ .Values.images.curl.tag }}
        command: ["sh", "-c", "until curl --silent http://database:{{ .Values.ports.database }}; do sleep 2; done"]
      - name: wait-for-vault-agent
        image: {{ .Values.images.curl.repository }}:{{ .Values.images.curl.tag }}
        command: ["sh", "-c", "until curl --silent http://vault-agent:{{ .Values.ports.vaultAgent }}/v1/sys/health; do sleep 2; done"]