apiVersion: apps/v1
kind: Deployment
metadata:
  name: ruuter
  namespace: {{ .Values.namespace }}
  labels:
    app: ruuter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ruuter
  template:
    metadata:
      labels:
        app: ruuter
    spec:
      containers:
      - name: ruuter
        image: {{ .Values.images.ruuter.repository }}:{{ .Values.images.ruuter.tag }}
        imagePullPolicy: {{ .Values.images.ruuter.pullPolicy }}
        ports:
        - containerPort: {{ .Values.ports.ruuter }}
        env:
        - name: application.cors.allowedOrigins
          value: {{ .Values.ruuter.env.corsAllowedOrigins | quote }}
        - name: application.httpCodesAllowList
          value: {{ .Values.ruuter.env.httpCodesAllowList | quote }}
        - name: application.logging.displayRequestContent
          value: {{ .Values.ruuter.env.displayRequestContent | quote }}
        - name: application.logging.displayResponseContent
          value: {{ .Values.ruuter.env.displayResponseContent | quote }}
        - name: server.port
          value: {{ .Values.ports.ruuter | quote }}
        - name: application.DSL.processedFiletypes
          value: {{ .Values.ruuter.env.processedFiletypes | quote }}
        - name: application.incomingRequests.allowedMethodTypes
          value: {{ .Values.ruuter.env.allowedMethodTypes | quote }}
        volumeMounts:
        - name: dsl
          mountPath: /DSL
        - name: constants
          mountPath: /app/constants.ini
          subPath: constants.ini
      volumes:
      - name: dsl
        emptyDir: {}
      - name: constants
        configMap:
          name: ruuter-config
      initContainers:
      - name: git-clone
        image: alpine/git:latest
        volumeMounts:
        - name: dsl
          mountPath: /DSL
        command:
          - sh
          - -c
          - |
            if [ ! -d "/DSL/centops" ]; then
              git clone --single-branch --depth 1 --branch helm-charts https://github.com/varmoh/CentOps.git /tmp/CentOps &&
              cp -r /tmp/CentOps/DSL/Ruuter/centops /DSL/;
            else
              echo "centops folder already present, skipping clone.";
            fi   
      - name: wait-for-vault-agent
        image: {{ .Values.images.curl.repository }}:{{ .Values.images.curl.tag }}
        command: ["sh", "-c", "until curl --silent http://vault-agent:{{ .Values.ports.vaultAgent }}/v1/sys/health; do sleep 2; done"]