apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tim-postgresql-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.volumes.timPostgresql.storage }}