apiVersion: v1
kind: Service
metadata:
  name: resql-users
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: resql-users
  ports:
  - protocol: TCP
    port: {{ .Values.ports.resqlUsers }}
    targetPort: {{ .Values.ports.resqlUsers }}
  type: ClusterIP