apiVersion: v1
kind: Service
metadata:
  name: resql
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: resql
  ports:
  - protocol: TCP
    port: {{ .Values.ports.resql }}
    targetPort: {{ .Values.ports.resql }}
  type: ClusterIP