apiVersion: v1
kind: Service
metadata:
  name: vault-agent
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: vault-agent
  ports:
  - protocol: TCP
    port: {{ .Values.ports.vaultAgent }}
    targetPort: {{ .Values.ports.vaultAgent }}
  type: ClusterIP