apiVersion: v1
kind: Service
metadata:
  name: ruuter
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: ruuter
  ports:
  - protocol: TCP
    port: {{ .Values.ports.ruuter }}
    targetPort: {{ .Values.ports.ruuter }}
  type: ClusterIP