apiVersion: v1
kind: Service
metadata:
  name: vault
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: vault
  ports:
  - protocol: TCP
    port: {{ .Values.ports.vault }}
    targetPort: {{ .Values.ports.vault }}
  type: ClusterIP