apiVersion: v1
kind: Service
metadata:
  name: centops-gui
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: centops-gui
  ports:
  - protocol: TCP
    port: {{ .Values.ports.centopsgui }}
    targetPort: {{ .Values.ports.centopsgui }}
  type: ClusterIP