extractRequestData:
  assign:
    cookie: ${incoming.headers.cookie}
  next: check_if_authorized 

check_if_authorized:
  template: templates/permissions/check-user-authority
  requestType: post
  headers:
    cookie: ${cookie}
  result: authority_result
  next: check_authority_result

check_authority_result:
  switch:
    - condition: ${authority_result !== "false"}
      next: get_participants_requests
  next: return_unauthorized

get_participants_requests:
  call: http.post
  args:
    url: "[#CENTOPS_RESQL]:[#CENTOPS_RESQL_PORT]/get-participants-by-status"
    body: 
      participant_status: 'unprocessed'
  result: participants_result

return_ok:
  wrapper: false
  status: 200
  return: ${participants_result.response.body}
  next: end

return_unauthorized:
  return: "error: unauthorized"
  status: 401
  next: end
