# TODO uncomment lines 2-5, use actual cookie from header for authentication.
# check_for_cookie:
#   switch:
#     - condition: ${incoming.headers == null || incoming.headers.cookie == null}
#       next: return_unauthorized

authenticate:
  template: templates/permissions/admin
  requestType: post
  headers:
    cookie: cookie #${incoming.headers.cookie}
  result: permission

validate_permission:
  switch:
    - condition: ${permission}
      next: get_participants_requests
  next: return_unauthorized

get_participants_requests:
  call: http.post
  args:
    url: http://resql:8052/get-participants-by-status
    body: 
      participant_status: 'unprocessed'
  result: participants_result

return_ok:
  wrapper: false
  status: 200
  return: ${participants_result.response.body}
  next: end

return_unauthorized:
  return: "error: unauthorized"
  status: 401
  next: end
