version: "3.8"

services:

  vault:
    image: hashicorp/vault:1.13
    container_name: vault
    restart: always
    ports:
      - "8200:8200"
    environment:
      VAULT_ADDR: "http://0.0.0.0:8200"
    volumes:
      - ./config.hcl:/vault/config/config.hcl
      - "${VAULT_DATA_PATH}/data:/vault/data"
    entrypoint: >
      vault server -config=/vault/config/config.hcl
    cap_add:
      - IPC_LOCK

  vault-agent:
      image: hashicorp/vault:1.13
      container_name: vault-agent
      depends_on:
        - vault
      cap_add:
        - IPC_LOCK
      volumes:
        - ./vault-agent.hcl:/vault/vault-agent.hcl
        - ./template.ctmpl:/vault/templates/template.ctmpl
        - "${VAULT_DATA_PATH}/.vault-token:/vault/secrets/.vault-token:ro"
        #- "${VAULT_DATA_PATH}/shared-secrets:/vault/secrets"
        - shared-secrets:/vault/secrets
      command: vault agent -config=/vault/vault-agent.hcl

  vault-unseal:
      image: curlimages/curl:latest
      container_name: vault-unseal-tool
      depends_on:
        - vault
      environment:
        VAULT_UNSEAL_KEY: ${VAULT_UNSEAL_KEY}
      entrypoint: sh
      command: -c '
        echo "Waiting for Vault to be started...";
        until curl --silent http://vault:8200/v1/sys/health | grep -q "\"initialized\":true"; do
        sleep 2;
        done;
        echo "Sending unseal key...";
        curl --silent --request PUT --data "{\"key\":\"$VAULT_UNSEAL_KEY\"}" http://vault:8200/v1/sys/unseal;
        echo "Vault Unseal done.";'

      restart: "no"

  app:
      image: alpine
      container_name: app-test
      volumes:
        - shared-secrets:/vault/secrets
      entrypoint:
        - sh
        - -c
        - |
          echo "Waiting for secrets file...";
          while [ ! -f /vault/secrets/app.env ]; do sleep 1; done;
          echo "Secrets file found:";
          cat /vault/secrets/app.env;

          # Source secrets, handling possible CRLF:
          tr -d '\r' < /vault/secrets/app.env > /tmp/app.env.clean
          . /tmp/app.env.clean

          echo "Running with USERNAME=$APP_USERNAME"
          sleep 3600

volumes:
  vault-data:
  shared-secrets:
