const publicAppUrl = import.meta.env.REACT_APP_PUBLIC_URL;

export const ROUTES = {
  APPLICATION_ROUTE: `${publicAppUrl}/application`,

  CLIENT_LIST_ROUTE: '/clients',
  CLIENT_DETAILS_ROUTE: '/clients/:clientId',
  CLIENT_SECRETS_ROUTE: '/clients/:clientId/secrets',
  CLIENT_SECRETS_DETAILS_ROUTE: '/clients/:clientId/secrets/:secretId?',
  CLIENTS_SECRETS_DIFF_ROUTE: '/clients/:clientId/secrets/:secretId/diff',
  CLIENT_CERTIFICATES_ROUTE: '/clients/:clientId/certificates',
  CLIENT_CERTIFICATES_CREATE_ROUTE: '/clients/:clientId/certificates/create',
  CLIENT_MANIFESTS_ROUTE: '/clients/:clientId/manifests',
  CLIENT_MANIFESTS_DETAILS_ROUTE: '/clients/:clientId/manifests/:manifestId?',
  USER_LIST_ROUTE: '/users',
  USER_DETAILS_ROUTE: '/users/:userId',
  CLUSTER_LIST_ROUTE: '/clusters',
  CLUSTER_DETAILS_ROUTE: '/clusters/:clusterId',
  DOCUMENTATION_ROUTE: '/documentation',
  DOCUMENTATION_EDIT_ROUTE: '/documentation/edit',

  INVITATION_ROUTE: '/invitation',
  OVERVIEW_ROUTE: '/overview',
  PARTICIPANTS_ROUTE: '/participants',
  PARTICIPANTS_REQUESTS_ROUTE: '/requests/participants',
  PARTICIPANTS_EDIT_ROUTE: '/participants/edit/:id',
  PARTICIPANTS_REQUESTS_EDIT_ROUTE: '/requests/participants/edit/:id',
  INSTITUTIONS_ROUTE: '/institutions',
  MESSAGES_PAGE_ROUTE: '/messages',
  MANIFESTS_ROUTE: '/manifests',
  MANIFESTS_OVERVIEW_ROUTE: '/manifests/overview',
  MANIFESTS_NEW_MANIFESTS_ROUTE: '/manifests/new_manifests',
  MANIFESTS_UPDATES_ROUTE: '/manifests/updates',
  MANIFESTS_HISTORY_ROUTE: '/manifests/history',
  MANIFESTS_DETAILS_ROUTE: '/manifests/details/:id',
  MANIFESTS_CREATE_EDIT_ROUTE: '/manifests/create_edit',
};
