check_body:
  switch:
    - condition: ${incoming.params.uniqueIdentifier == null}
      next: return_incorrect_request

get_participant:
  call: http.post
  args:
    url: http://resql:8052/get-participant-by-id
    body:
      unique_identifier: ${incoming.params.uniqueIdentifier}
  result: participant_result

return_success:
  status: 200
  return: ${participant_result.response.body[0].participantStatus}
  next: end

return_incorrect_request:
  status: 400
  return: "Missing required parameters"
  next: end
