spring:
  application:
    name: secret-manager
  cloud:
    vault:
      host: ${VAULT_HOST}
      port: ${VAULT_PORT}
      scheme: ${VAULT_SCHEME}
      authentication: token
      token: ${VAULT_TOKEN}
      kv:
        enabled: true
        backend: secret
        profile-separator: '/'
      fail-fast: true
      connection-timeout: 5000
      read-timeout: 15000

server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    ee.buerokratt.secretmanager: ${LOG_LEVEL:INFO}
    org.springframework.vault: ${VAULT_LOG_LEVEL:INFO}
    org.springframework.cloud.vault: ${VAULT_LOG_LEVEL:INFO}