name: Code Check, Build

on:
  pull_request:
    branches: ["dev", "test", "stage", "main"]

env:
  BRANCH: ${{ github.head_ref || github.ref_name }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: "Run ESLint"
        run: |
          cd GUI
          npm run lint

      - name: "Check Prettier formatting"
        run: |
          cd GUI
          npm run format
